export const image = (name: string) => `/demos/images/${name}.webp`;
export const properties = [
  {
    id: "villa-horizon",
    title: "Villa Horizon",
    city: "Uccle",
    type: "Villa",
    price: 1250000,
    area: 285,
    beds: 4,
    image: "estate-hero",
    tag: "EXCLUSIVITÉ",
    address: "Quartier du Prince d’Orange",
    description:
      "La lumière comme fil conducteur. Une villa ouverte sur son jardin, des volumes généreux et une terrasse qui prolonge naturellement les pièces de vie.",
    energy: "B",
    land: 1200,
    features: [
      "Jardin arboré",
      "Terrasse plein sud",
      "Garage double",
      "Suite parentale",
    ],
    lat: 50.792,
    lon: 4.366,
  },
  {
    id: "loft-lumiere",
    title: "Le Loft Lumière",
    city: "Bruxelles",
    type: "Appartement",
    price: 645000,
    area: 168,
    beds: 3,
    image: "estate-interior",
    tag: "NOUVEAUTÉ",
    address: "Quartier des Étangs d’Ixelles",
    description:
      "Un appartement aux lignes pures, où les matières naturelles rencontrent une belle hauteur sous plafond. Le calme, à deux pas de la ville.",
    energy: "C",
    land: 0,
    features: ["Terrasse de 24 m²", "Ascenseur", "Cuisine ouverte", "Bureau"],
    lat: 50.826,
    lon: 4.373,
  },
  {
    id: "maison-des-arts",
    title: "Maison des Arts",
    city: "Waterloo",
    type: "Maison",
    price: 875000,
    area: 230,
    beds: 4,
    image: "estate-house",
    tag: "COUP DE CŒUR",
    address: "À proximité du centre",
    description:
      "Une adresse familiale avec du caractère. De belles pièces de réception, quatre chambres et un jardin intime composent un quotidien à votre rythme.",
    energy: "B",
    land: 650,
    features: [
      "Jardin privatif",
      "Cheminée",
      "Quatre chambres",
      "Proche des écoles",
    ],
    lat: 50.715,
    lon: 4.399,
  },
  {
    id: "penthouse-jardin",
    title: "Penthouse Jardin",
    city: "Bruxelles",
    type: "Appartement",
    price: 980000,
    area: 195,
    beds: 3,
    image: "estate-terrace",
    tag: "DERNIER ÉTAGE",
    address: "Quartier du Châtelain",
    description:
      "Au-dessus de la ville, une parenthèse de calme. Une terrasse panoramique et des espaces lumineux dessinent une autre façon d’habiter Bruxelles.",
    energy: "A",
    land: 0,
    features: [
      "Terrasse panoramique",
      "Parking",
      "Pompe à chaleur",
      "Dernier étage",
    ],
    lat: 50.824,
    lon: 4.358,
  },
  {
    id: "villa-cedres",
    title: "La Villa des Cèdres",
    city: "Lasne",
    type: "Villa",
    price: 1495000,
    area: 350,
    beds: 5,
    image: "estate-pool",
    tag: "COLLECTION PRESTIGE",
    address: "Au cœur du Brabant wallon",
    description:
      "Une maison pensée pour recevoir, entourée de verdure. Des ouvertures généreuses, une piscine et une atmosphère sereine.",
    energy: "B",
    land: 2400,
    features: ["Piscine", "Parc paysager", "Cinq chambres", "Dépendance"],
    lat: 50.687,
    lon: 4.48,
  },
  {
    id: "maison-patio",
    title: "La Maison Patio",
    city: "Uccle",
    type: "Maison",
    price: 720000,
    area: 185,
    beds: 3,
    image: "estate-house",
    tag: "À DÉCOUVRIR",
    address: "Quartier du Fort Jaco",
    description:
      "Une maison accueillante, organisée autour d’un patio. Des espaces bien proportionnés et une adresse idéale pour une vie de quartier.",
    energy: "C",
    land: 320,
    features: ["Patio", "Garage", "Trois chambres", "Commerces à pied"],
    lat: 50.796,
    lon: 4.363,
  },
];
export const menu = [
  {
    id: "burrata",
    category: "Entrées",
    name: "Burrata, tomates de saison",
    detail: "Basilic frais, huile d’olive fruitée, pain au levain",
    price: 16,
    image: "food-burrata",
    tags: ["Végétarien"],
    allergens: "Lait, gluten",
  },
  {
    id: "tartare",
    category: "Entrées",
    name: "Tartare de bœuf au couteau",
    detail: "Câpres, échalotes, jaune d’œuf et toast croustillant",
    price: 19,
    image: "food-steak",
    tags: [],
    allergens: "Œuf, gluten, moutarde",
  },
  {
    id: "bavette",
    category: "Plats",
    name: "Bavette à la braise",
    detail: "Jus corsé, pommes de terre grenailles, légumes rôtis",
    price: 32,
    image: "food-steak",
    tags: ["Signature"],
    allergens: "Lait, céleri",
  },
  {
    id: "poisson",
    category: "Plats",
    name: "Poisson du marché",
    detail: "Beurre blanc citronné, légumes de notre maraîcher",
    price: 29,
    image: "food-fish",
    tags: [],
    allergens: "Poisson, lait",
  },
  {
    id: "risotto",
    category: "Plats",
    name: "Risotto des sous-bois",
    detail: "Champignons, parmesan affiné et herbes fraîches",
    price: 25,
    image: "food-risotto",
    tags: ["Végétarien"],
    allergens: "Lait",
  },
  {
    id: "chocolat",
    category: "Desserts",
    name: "Le chocolat, tout simplement",
    detail: "Ganache intense, crumble cacao, fleur de sel",
    price: 12,
    image: "food-dessert",
    tags: ["Signature"],
    allergens: "Lait, œuf, gluten",
  },
  {
    id: "tarte",
    category: "Desserts",
    name: "Tarte fine aux fruits",
    detail: "Fruits de saison, crème légère à la vanille",
    price: 11,
    image: "food-dessert",
    tags: ["Végétarien"],
    allergens: "Lait, œuf, gluten",
  },
];
export const wines = [
  {
    name: "Domaine des Roches · Loire",
    type: "Blanc",
    notes: "Chenin · minéral, vif, notes d’agrumes",
    glass: 8,
    bottle: 39,
  },
  {
    name: "Les Hauts de Ségur · Bordeaux",
    type: "Rouge",
    notes: "Merlot & Cabernet · fruits noirs, tanins soyeux",
    glass: 9,
    bottle: 45,
  },
  {
    name: "Cuvée des Collines · Provence",
    type: "Rosé",
    notes: "Grenache · délicat, sec et floral",
    glass: 8,
    bottle: 38,
  },
  {
    name: "Brut Réserve · Champagne",
    type: "Bulles",
    notes: "Chardonnay & Pinot noir · bulle fine et brioche",
    glass: 14,
    bottle: 72,
  },
];
export const projects = [
  {
    id: 1,
    title: "Un jardin pour ralentir",
    city: "Lasne",
    category: "Création",
    image: "garden-hero",
    area: "420 m²",
    text: "Des graminées, des cheminements en pierre et des espaces de vie reliés par une même palette végétale.",
  },
  {
    id: 2,
    title: "La terrasse devient un lieu",
    city: "Waterloo",
    category: "Terrasses",
    image: "garden-terrace",
    area: "65 m²",
    text: "Une terrasse en bois, un coin repas et des plantations qui installent une intimité naturelle.",
  },
  {
    id: 3,
    title: "Une nouvelle vie dehors",
    city: "Uccle",
    category: "Entretien",
    image: "garden-detail",
    area: "280 m²",
    text: "Remise en forme des massifs, taille raisonnée et entretien saisonnier pour retrouver un jardin équilibré.",
  },
  {
    id: 4,
    title: "Une baignade au naturel",
    city: "Rixensart",
    category: "Piscines naturelles",
    image: "garden-pool",
    area: "90 m²",
    text: "Un bassin qui dialogue avec le paysage, des berges plantées et une approche naturelle du jardin.",
  },
];
